package com.zodiackillerciphers.ciphers;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

/** based on Bob Bogart's talk about the diary with portions enciphered using a shifting scheme:
 * shift plaintext by +/- N, where +/- is chosen randomly.
 */
public class HaferShiftCipher {
	static Random rand = new Random();
	public static String encode(String plaintext, int N) {
		plaintext = plaintext.toUpperCase();
		String cipher = "";
		for (int i=0; i<plaintext.length(); i++) {
			if (rand.nextBoolean())
				N = -N;
			cipher += shift(plaintext.charAt(i), N);
		}
		return cipher;
	}
	/** decoding produces 2 possible strings.  analyst has to decide how to mix them to produce solution. */
	public static String[] decode(String cipher, int N) {
		cipher = cipher.toUpperCase();
		String[] plaintexts = new String[2];
		plaintexts[0] = "";
		plaintexts[1] = "";
		for (int i=0; i<cipher.length(); i++) {
			char c = cipher.charAt(i);
			plaintexts[0] += shift(c, -N);
			plaintexts[1] += shift(c, N);
		}
		return plaintexts;
	}
	/** shift given uppercase character by 1. */  
	public static char shift(char ch, int N) {
		int i = ch - 65;
		i = (i + 26 + N) % 26;
		return (char) (i+65);
	}

	/**
	 * make some homophonic ciphers using plaintexts that are encoded using
	 * arbitrary shifts
	 */
	public static String[] plaintexts = new String[] {
			Ciphers.Z408_SOLUTION.substring(0, 340),
			"INTHESANDHILLSWASABOYNAMEDMORTENHEANDJRGENLEFTTHEFISHINGANDTHEYBOTHHIREDTHEMSELVESONBOARDAVESSELBOUNDTONORWAYANDWENTAFTERWARDSTOHOLLANDTHEYWEREALWAYSATODDSWITHEACHOTHERBUTTHATMIGHTEASILYHAPPENWHENPEOPLEWERERATHERWARMTEMPEREDANDTHEYCOULDNOTHELPSHOWINGTHEIRFEELINGSSOMETIMESINEXPRESSIVEGESTURESTHISWASWHATJRGENDIDONCEONBOARDWHENTHEYCAMEUPFROM",
			"NOTATDUSKORINTHEDARKTHISWASSENSIBLEENOUGHGTOGIVEUPEVERYTHEYAGAINSTWHILEHETALKEDFLUENTLYABOUTTHENECESSIEIGHTMILESMEANTNEARLYTHREEHOURSSTEAMINGFORUSANDICOULDALSOSEESUSPICIOUSRIPPLESATTHEUPPERENDOFTHEREACHNEVERTHELESSIWASANNOYEDBEYONDEXPRESSIONATTHEDELAYANDMOSTUNREASONABLYTOOSINCEONENIGHTMORECOULDNOTMATTERMUCHAFTERSOMANYMONTHSASWEHADPLENTYOF",
			"NOWNEARLYFOURYEARSNEARERTHEHEAVENLYHARBORWHEREDESTRUCTIVEGALESOFTEMPTATIONWILLNEVERSWEEPTHEWHITESAILSOFPURITYFROMTHEMASTSOFPURPOSENORBREAKTHEYARDARMSOFEFFORTNORROLLINGBREAKERSOFINIQUITYDASHHERUPONTHEROCKYSHOREOFETERNALRUINMOTHERPLEASEGIVEMYKINDESTWISHESTOALLWHOAREHELPINGYOUINTHEGREATWORKWHICHJESUSESTABLISHEDWHILEONEARTHANDWHICHHELEFTFORUS",
			"OFEVILDOERSCHILDRENTHATARECORRUPTERSSHEEPTHATHAVEWANDEREDAWAYFROMTHESHEPHERDANDBISHOPOFTHEIRSOULSINTHEADJUDICATIONOFSCRIPTURETHEREISNOEXEMPTIONFROMTHISCOMMONCHARACTEROFEVILANDFROMTHISCOMMONEXPOSURETODANGERTHEMENOFMERCIFULCHARITIESANDTHEWOMANOFABANDONEDLIFETHEPROUDESTPEERANDTHEVILESTSERFINHISBARONYTHEMORALISTOBSERVEROFTHEDECALOGUEANDTHEMAN",
			"OFTENDOESCOURTTOMODESTEARTHLYLADIESHEISPROPERLYSOMEWHATOFAFLIRTTHATISUNBECOMINGANOLDMANYESBUTHEISNOTOLDOHSAIDMISSHJELMLAUGHINGIHAVEONLYKNOWNONEWARCOUNSELLORANDHEWASOLDSOITHOUGHTOFALLWARCOUNSELLORSASOLDYESBUTCOUNSELLORBAGGERISNOTWARCOUNSELLORBUTAREALSUPERIORCOURTCOUNSELLOROHHOWEARNESTTHATISANDSOHEISINLOVEWITHAFAIRYYESITISRIDICULOUSSAIDMISS",
			"REQUIRENTTRSINSTAMMENTOULTRELACRANCEDUDICTSETONQUIESTOITAUSSYDEMMEDESECOURIRETASSISTERMADICTESOEURLAROYNEDESCOSSESURQUOYJERESPONDISLARCHEVESQUEDEGLASCOETAUDICTSETONCOMMEAUSSIFISTMADICTEDAMEETMREDESONCOSTQUENOUSAVIONSFAICTCEQUIAVOITESTPOSSIBLECOMMEENCORENOUSFAIRIONSTOUJOURSPOURLARESTITUTIONDEMADICTESOEURLAROYNEDESCOSSEMAISPARCEQUELAROYNEMA",
			"SAMEVOLUMETHISNEVERHAPPENEDBYCHANCECLEARLYTHEYAREACQUAINTANCESANDAREWORKINGTOGETHERTOWARDSOMECOMMONENDISHOULDTHINKITVERYLIKELYJUDGINGFROMTHEIRINTERESTINCANCERSANDTOXICOLOGYTHATTHEYWEREMEDICALSTUDENTSNUMBERSFOURANDFIVEDONTEXACTLYSEEMTOSTRENGTHENMYMEDICALHYPOTHESISBUTTHEYAREONLYTWOOUTOFTHETENTHATSABOUTALLICANMAKEOUTOFITANDIRETURNEDTHELISTTO",
			"TALLOUGHTTOBEHEALTHYFELLOWSWITHMYCOMMERCIALRATINGAREIMMUNEFROMITIHAPPENEDTOBEVISITINGAFRIENDINASMALLTOWNFORAFEWDAYSANDWASACQUIRINGAVORACIOUSAPPETITEONEEVENINGIWASSEIZEDWITHASUDDENPAINANDIKNEWTHEDREADDISEASEHADCOMEATLASTTHEDOCTORCAMEHEWASANOLDFASHIONEDFELLOWWITHOUTANYFRILLSBUTHEHADWHATBOOKSANDCOLLEGESDONOTALWAYSBESTOWAHEADFULLOFCOMMONSENSE",
			"TOLIFTTHEMORELSEHOLESMUSTBECUTINTHEMFORTHISPURPOSEVIDEFIGFRAMESFORPICTURESORLOOKINGGLASSESTHESEGIVEAWIDERANGETOTHEWOODCARVERFORALLBORDERSARESUITABLETOFRAMESHEADSMAYBEAPPLIQUTOCORNERSANDCENTRESOFFRAMESITISVERYMUCHTOBEDESIREDTHATDESIGNERSANDCARVERSWOULDEXERTTHEIRINVENTIVENESSANDENDEAVOURTOBREAKUPTHEMONOTONYANDFEEBLENESSWHICHCHARACTERIZEMOST" };; 
		public static String[] plaintextsJarlve = new String[] {
				"ONIACKILLINGPEOPLEBECAUSEITISSOMUCHFUNITISMOREFUNTHANKALLINGWILDCAMEINTHEFORTESTDEXCUSEMYLISTHEMOATDENIERTWEENAMALOFALLTOKILLSOMETHINGCAKESMETHEBOATTHRILLINGCINGRENEEITISEVENBETTERTHANGERTONEYOURROAISOFFWITHAGIRLTHEBESTPARTOFARCATHCEWHENIDIEIWILLBEREBORNINPARADIAGULFALLTHEIHATECOLLEDWILLBECOMEMYSNAKESAWALLPMTICKEYBUMENAMEBECAUSEYOUWILLTRY",
				"INTHEWARDHILLSWAKENBYNAMEDMARTACHEANDJRGENLEFTTHEFISHINGANDTHEYBOTHLIVEDTHEMSELVESONBOARDAVESKILBOUNDTONONEAUANDWENTAFTEREANDSTOHOLLANDTHEYWEREALSATSATODDSEITHEACHOTHERBUTTHATMIGHTEASILYHAPPENWHENPEOPLESEVERATHERWARMTEMPEREDANDTHEYCOULDNOTHELPSHOEINGTHEIRFEELINGSSOMETIMESINIBPRESSIVECIATURESTHISWASSHIPFRCANDIDACTIONBOARDWHENTHEYCAMEUPFROM",
				"NOTATDUSKONERTHEDARKTHEWAASSERSIBLEENOUGHGTOGIVEUPEVERYTHEYAGAINSTWHILEHETALKEDFLUENTLYALBUTTHERECESSEEIGHTMILESMEARTNEARLYTHREEHOURSSTEAMINGFORUSANDICOULDALSOBEASUSPICIOUSRIPPLESATTHEUPPERANDOFTHEREACHREVERTHELESSIWASANNOYEDBEYONDEXPRESSIONATTHEDELAYANDMOSTUNREASONALLYTOOSINCEONENIGHTMOVECOULDNOTMATTERIUCHAFTERSOMANYMONTHSASWEHADPLENTYOF",
				"NGONEARLYYOURSEARANMORERTHEHEADEDLYHARBORWHEREDESTRUCTIVEGAMESONTEMPTATIONWILLNEVERSEEMPTHEWHILESAIDSOFPCHATSFROMTHEEASTSONPURPOSENORTHWASTHEYAREARUSOFENFORINGWHOLDINGTWEAKERSONONASUITYJOSHHERUPONTHEROCKSSHORMODETERNALRUIDEOTHERPLEASEGINMESKINDEALWISHESTOAMLWHOAREHELPINGYOUINTHEGREATMORKWHICHBESUSESTABLISHEDEHOMEONEARTHANDWHICHHEMENTFORUS",
				"OREHISDOERSCHILDRENTHATARECORRUPTERSSHEEPTHATHAVEWANDEREDAWAYFROMTHESTEPHERDANDBISTOPOFTHEIRSOULSINTHEADVIDICATIONOFSCRIPTURETHEREISNOELEMPTIONTROYTHISCOMMONCHARACTERAREVILANDFROMTHISCOMMONEXPOSURETODANGERTHEMENOFMERCIFULCHARITIESANDTHEWOMANOFAPANDONEDKITETHEPRAGDEETPEERANDTHEVILSETSEFFINHISBADANDTHEMORALISTOBSERVEROFTHEDECALOGUEANDTHEMAN",
				"",
				"",
				"SAMENODCOWTHISNEVERHAPPENEDBYCHANCECLEARTYTHEYAREACQUAINTANCESANDAREWORKINGTOGETHERTOWARDSOMECOUMONENDASHOULDTHINKITNERILIKELYBUDGINGFROMTHEARINTERESTINCANCERSANDTOFACOLOGYTHATTHEYWEREUMPICATSTUDENTSNUUTORSFOURINLFINELONTEXACTLIKEMETOSTRONGTHEFUGUEVACATHGHOTHESASBUTTHEYAREONLYTWOOUTOFTHETENTHATSABOUTALLICANMAKEOUTOFITANDARETURNEDTHELISTTO",
				"TILLEEGOTTOBEREALTHOFELLOWSMITHCOCOMMERCIALRATINGAREIMMUNEPREMITSHAPPENEDTOBEFIRSTINGAFRIENDINASMALLDOWNFORAFEWDAYSANDWASACQUIRINGALEVICIOUSAPPETITEONEELEDINWIGASSEIZEDWITHARUNNEDPAINANDSANEWTHENBEANDISEASEVANCOMEATLASTTHENORTOBRAWEHEWASANOLDFASHIONEDFELLOWGSTRYKDANOFRILLSBETHEVANWHATBOOKSANDCOLLEGESDENOTALWAYSBESTOWAREADFULLYFROMMONRENSE",
				"TOFOFFTHEMORELSEHOLESMUSTBECUTINTHEMFORTHISPURPOSEBODEFOALLASEYFIXPICTURESORLOOKINGGLASSESTHESEGIVEACODELAHGETONBYWOODCARPERFORALLHOLDERSARESUITABLETOFRAMESHEADSMAYBEAPPROVATOCORNERSANDCENTRESOFFRAMESITISVERYSAINTIVEDESIREDTHATDESIGNERSANDCARVERSWOULDEXERTTHEIRINVENTIVENESSANDENDEADIALTOBREAKUPTHEMINUTONEANDLEEBLENESSWHICHCHARACTERITYSUST"		
		};
	public static void makeHomophonics() {
		Set<Integer> done = new HashSet<Integer>();
		String[] pt = plaintexts; 
		for (String p : pt) {
			int N;
			do {
				N = rand.nextInt(13) + 1;
			} while (done.contains(N));
			done.add(N);
			String encoded = encode(p, N);
			String hom = HomophonicGenerator.makeHomophonic(encoded, 63);
			System.out.println(N);
			System.out.println(p);
			System.out.println(encoded);
			System.out.println(hom);
		}
		/* the ones I gave to Jarl:  http://zodiackillersite.com/viewtopic.php?p=81508#p81508
		 
			1
			ILIKEKILLINGPEOPL
			EBECAUSEITISSOMUC
			HFUNITISMOREFUNTH
			ANKILLINGWILDGAME
			INTHEFORRESTBECAU
			SEMANISTHEMOATDAN
			GERTUEANAMALOFALL
			TOKILLSOMETHINGGI
			VESMETHEMOATTHRIL
			LINGEXPERENCEITIS
			EVENBETTERTHANGET
			TINGYOURROCKSOFFW
			ITHAGIRLTHEBESTPA
			RTOFITIATHAEWHENI
			DIEIWILLBEREBORNI
			NPARADICESNDALLTH
			EIHAVEKILLEDWILLB
			ECOMEMYSLAVESIWIL
			LNOTGIVEYOUMYNAME
			BECAUSEYOUWILLTRY
			
			JMJJFLJMMHOHOFPQK
			FCDBBTRDHSHRRNLVB
			IEVMHUHTLPSDEVMSI
			BMLJMKJOHXJKCFBLF
			JMSGDGNQSFTUCFBBT
			TFNZMHRSIFLPBUCZO
			HFQUVDZOZNZKNEBMM
			UNLHMKTPNDSIHOFFJ
			WDRNDUIDNPZSUGQHM
			KJMFDWOFSFMDFHSHR
			DWDOADUUDSUGBMHFS
			UJMFXPVQSPBJRNGGX
			HUIBHHSKUIDCFTUOB
			QUNEJSJBSGBDXGFMH
			EHDHVHKMADQFCPSMH
			MQZSBCJBFRMEBMMUI
			DJIZUFJJMMFEVHKKC
			FDPLFLXTMBWFRJVJM
			MONSHJWDXNTLZOBND
			CDBZVTDZPVXJKMUSX
			
			S6R*z|R%1U;UOzq4C
			z#_TbcLMUGBLLZ^<D
			)V<6U2Bc^qGtV9-G3
			T6|@-CR;UWR7#zb^z
			R-GJ_J>4&z+2F5ND+
			+zZ.1BL&)5|qd2Fy;
			B542pty;.Z.7YE(%-
			2K|B-7+q>A&38O5z@
			P_LXt2)A/q.G2J4f1
			CR-5tP;5&5-HzU&BL
			HlA;j_22AG2Jb6Uz&
			2S6zWq:4&qbRLZJJW
			82)bUU&C23kFzc2Ob
			42YE*G@bGJDMWJz-f
			VfAU:BC1jM45Fq&%8
			14.Gd#Rb5L6E(612)
			AR3.25@S11zVpU77#
			ztq|5^W+6(PzL*9*-
			6OX&f@P_W/+|y;TXk
			Fkd.9+H.q:WR712&W

			11
			INTHESANDHILLSWAS
			ABOYNAMEDMORTENHE
			ANDJRGENLEFTTHEFI
			SHINGANDTHEYBOTHH
			IREDTHEMSELVESONB
			OARDAVESSELBOUNDT
			ONORWAYANDWENTAFT
			ERWARDSTOHOLLANDT
			HEYWEREALWAYSATOD
			DSWITHEACHOTHERBU
			TTHATMIGHTEASILYH
			APPENWHENPEOPLEWE
			RERATHERWARMTEMPE
			REDANDTHEYCOULDNO
			THELPSHOWINGTHEIR
			FEELINGSSOMETIMES
			INEXPRESSIVEGESTU
			RESTHISWASWHATJRG
			ENDIDONCEONBOARDW
			HENTHEYCAMEUPFROM
			
			TYISTHPCOWXWWDHPD
			LMZNCLXPSXDCIPYSP
			LCSYGRPYWPUIESPUX
			DWTCRLYOISPJMZESW
			XGPSIWTXHPAGPDDCM
			DLGOLGPDDTWMZFYOE
			ZCDCLPJPCSHPCEPUE
			PCLLCODEZSZAWPCOE
			STNHPCTPAHLNHLIDS
			SHLXEWTLNWDESPGMJ
			IEWPIBTRSEPLDTWNS
			LAEPCHSPYEPZEAPHT
			GPGLISTCHLCBITXEP
			GPSPCSIWTNRDFASCZ
			EWPAEHWZLTYRISPXC
			QPTATYVDDDBPIXBTD
			XCTMECTDDXGPRTDEF
			GPHIWTHHLDHWPEUGR
			PYSTODYNPZCMDLGSH
			WTYIWPJNLBPFEQCZB
			
			BF6JCNA@t)GK)_N*#
			(>/|X(G8JGVX.AqRA
			(@OFc-8FE8W.DJlWG
			_)BH-(^&.y8Ljzf2E
			Gc8J.EBG9*%c5_7Xj
			7(c&(c5_#CEjz4^&D
			<H_X(5L8@R9lHU5Wf
			A@((@&_fzJ+bE8Xtp
			JC|95XB5bd(Md(._J
			yd(GfTB(|)_py*cjL
			1DTA63C-JU*(_CK;y
			(%flH9R*FDlzpbldC
			clc(1JB@9(H36CGDA
			cAy8@J6KCS-#4by@z
			f)5%DdK<(BY-12AG@
			Z*C%B^:7__3A.k3C_
			kXBjfXC_7Gcl-BVf4
			c896TC99(7dTPDWc-
			*^JCtVqMP<@j#(c2N
			)BF1T*L|(354pZHz3
			
			2
			NOTATDUSKORINTHED
			ARKTHISWASSENSIBL
			EENOUGHGTOGIVEUPE
			VERYTHEYAGAINSTWH
			ILEHETALKEDFLUENT
			LYABOUTTHENECESSI
			EIGHTMILESMEANTNE
			ARLYTHREEHOURSSTE
			AMINGFORUSANDICOU
			LDALSOSEESUSPICIO
			USRIPPLESATTHEUPP
			ERENDOFTHEREACHNE
			VERTHELESSIWASANN
			OYEDBEYONDEXPRESS
			IONATTHEDELAYANDM
			OSTUNREASONABLYTO
			OSINCEONENIGHTMOR
			ECOULDNOTMATTERMU
			CHAFTERSOMANYMONT
			HSASWEHADPLENTYOF
			
			LMRYVBWUIQPGPVFGF
			CTIRJGUYCQUCPQGZJ
			GGPQWIJERMEKTCWNG
			XGPARFCACIYKLURUF
			KJGFCVCJICBHJSGLV
			JWCDQSVRJGPCECUQG
			CKIFROKNGUOCCPRPG
			YTJWRFTCCJMWPUQRG
			YKGLIHMPSQCPBGAMS
			NBYJUQQGCQSQNKAKQ
			WQTGNRJCUCRRFGWRN
			GPCPBQHVJCPCYAFPG
			TCPRJGNCQQKYCQYPL
			QWGBZCWQLBCZNPCUQ
			KQLCRVJGFCNYWYPBO
			MQRSLPGYQQLYDNAVM
			MUKLAGQPCLKEFVKQT
			GEMWJFPMROYVVGTKW
			AJCHVCPUQOCLWOMPR
			JUYUUGJYBRJGLVWQH
			
			H@.At5qOU%V7#RLDL
			+kU./7OA+%G^|WZ_E
			DBV%qU/J.@J8k6q)F
			PF#b:L^b^U>8HG:OL
			8/DLNK+/U6fj39pHK
			/q^129t:Ep#6J6l%Z
			NSUL:4S-DG<++|:T7
			>(*q:LkN+d@qzOM.B
			>8BHUj@|9%NTcBb@9
			)&>dlM2DN%9M-8bSW
			qM(Z).*+O+..LBq.-
			Z#NVf%YRd6|6AbL#D
			kNz.*Z-^MM8>+%AVX
			Mq7f_+qMHc6_-V^lM
			8WX6:;EFL+)>qATf<
			@M.9X|DAMMC>1-bt@
			@OSCbZWT^CSJLt8Wk
			BJ@q*LV@:4A;KD(Sq
			b36jK6|O%y^Hq<@T.
			dO>OOB3>&:37HtqWY
			
			4
			NOWNEARLYFOURYEAR
			SNEARERTHEHEAVENL
			YHARBORWHEREDESTR
			UCTIVEGALESOFTEMP
			TATIONWILLNEVERSW
			EEPTHEWHITESAILSO
			FPURITYFROMTHEMAS
			TSOFPURPOSENORBRE
			AKTHEYARDARMSOFEF
			FORTNORROLLINGBRE
			AKERSOFINIQUITYDA
			SHHERUPONTHEROCKY
			SHOREOFETERNALRUI
			NMOTHERPLEASEGIVE
			MYKINDESTWISHESTO
			ALLWHOAREHELPINGY
			OUINTHEGREATWORKW
			HICHJESUSESTABLIS
			HEDWHILEONEARTHAN
			DWHICHHELEFTFORUS
			
			RKSRIEVPCBSYNUAEN
			WRIENANXDIDAEZIJH
			CLWNFSNSDINIZIWXV
			YGPERIKEHAOSJXAIT
			XWXMSJSMHPRARIVWA
			AILPDIADMPAOEEHOS
			BTYNEXUBNSIXDIIWO
			POKJTYNLKWIRSVFNA
			WOPDICENZEVQWSBIJ
			BSVXRKNNKPHERKXNI
			EGIVWSJEREUYEXCZE
			ODLAVQTKJPLAVSYGU
			WDSVASJIPIVREHNQM
			JIKXDANLHIEOAKERA
			IUGMJZIWPAMWLIOPK
			WHHSDKENALIPTMRKC
			KQMRXLAKVAEPAKNGS
			LEYDFIOQOIOXWXHMW
			LIZADEHIKRAEVXLEJ
			ZSLEGLLAHIJXBSVQO
			
			7tV7G:k@j|V^Af)cY
			37TpA)A5/d/)c6d>N
			jqKY&VAV.GAG6GK5k
			^HOcWTUC8)R;*<)Tl
			13<_V*V_N@7)WGk3)
			bTZO/Pb._O)E:cyRV
			4l2#C5f4AVP1/DGJE
			ORUSlMYZUXd7;k&#b
			XE@zTjCA-ck9X;4D*
			%;k(7t+#tOy:7t5+D
			cHdk3;*pWCfM:5jFp
			E.qbk9lU*OqbkV2Hf
			XzVk)V>T@DkWcNY9B
			>dULz)YZNPCE)tc7)
			DfHBS6DXObBXqGEOt
			X8NV/U:Y)ZDOlBWtj
			t9_W<q)Uk)CO)tYHV
			qc2.&PE9RdRLX1NBX
			ZG6)zp8TU7):k5q:*
			6VqcHqq)8PS14Vk9R
			
			6
			OFEVILDOERSCHILDR
			ENTHATARECORRUPTE
			RSSHEEPTHATHAVEWA
			NDEREDAWAYFROMTHE
			SHEPHERDANDBISHOP
			OFTHEIRSOULSINTHE
			ADJUDICATIONOFSCR
			IPTURETHEREISNOEX
			EMPTIONFROMTHISCO
			MMONCHARACTEROFEV
			ILANDFROMTHISCOMM
			ONEXPOSURETODANGE
			RTHEMENOFMERCIFUL
			CHARITIESANDTHEWO
			MANOFABANDONEDLIF
			ETHEPROUDESTPEERA
			NDTHEVILESTSERFIN
			HISBARONYTHEMORAL
			ISTOBSERVEROFTHED
			ECALOGUEANDTHEMAN
			
			ILYBOFXUYLMIBCRJX
			YTZBGZULYIUXLOVZK
			XMMNKYVZBUNBGPYCG
			HJKXYJUCGSLXIGZNK
			MNYVNYXJUTXHOMNIV
			ILNBYOXMIARMOTNBY
			UXPOJCIUZCUTULYWL
			CVZOLKZBYLKOMTIKR
			YSVNOUTZXUSNNOMWI
			GSIHIBUXUINKLULKP
			ORGHJZXUSNNOYIUGG
			UHKDVUMALKZUJGTMK
			LZBYSKTULSKLWOZOF
			IBULCZCKYUHJZBYQI
			GUHULGVUHXUTYXFOZ
			YNNKVXUAJKYNVKYXG
			HXNBKPCRYYZYYLZOH
			BCMHGXUTEZNYSIXUF
			OMZUHMKLPKXIZZBKJ
			KWGFUAOKGHXZNKGGH
			
			PpT>Z_k.qfYd>&#1k
			(WE>A/SpqPBkf7XV4
			kY@U4(XV>S%>AGT8D
			:1*l^1+8DcpkHD3%y
			YLqX%(k1.Wk:bMLdX
			Hf%>^Zl@H)#@btU>^
			SkGZ1&H.z8NtNfC5f
			8XzZp4z>^F*ZMtH*#
			qcX%bJtElBc%%bYOd
			DcP:H>-k6PL*FSf*G
			b#A:13lBcUUb2d.AA
			N:;9X.M)p4E.1At@*
			pE>^c*W6fcyf5737K
			H>Sp&z8*(N:1V>q<H
			D6:6fAXS:l6W(kjb|
			^%U;Xl-)1*T%X4qlA
			:kU>*G&#CqE(^pV7:
			>8M:AlStR|UqcPl.K
			ZYzN:@;fG;lPV|>y1
			;5DK6)Z;A:lz%4AA:
			
			12
			OFTENDOESCOURTTOM
			ODESTEARTHLYLADIE
			SHEISPROPERLYSOME
			WHATOFAFLIRTTHATI
			SUNBECOMINGANOLDM
			ANYESBUTHEISNOTOL
			DOHSAIDMISSHJELML
			AUGHINGIHAVEONLYK
			NOWNONEWARCOUNSEL
			LORANDHEWASOLDSOI
			THOUGHTOFALLWARCO
			UNSELLORSASOLDYES
			BUTCOUNSELLORBAGG
			ERISNOTWARCOUNSEL
			LORBUTAREALSUPERI
			ORCOURTCOUNSELLOR
			OHHOWEARNESTTHATI
			SANDSOHEISINLOVEW
			ITHAFAIRYYESITISR
			IDICULOUSSAIDMISS
			
			CRFSBPAQEQCIDHFAY
			APQEFQOFHVZMZMPUS
			ETQWGBFABSDZMGCAS
			KTMHATOTXWFHHTOHU
			GIBNSOCAUZSMZAXRY
			MZMQGPGFTSWEBCFAZ
			RATEOWRAWEGVXSZYZ
			OIUVWZSWVMHSCZZKW
			ZCKBABSKODOCIBEQZ
			XCDMBRTSKOGAXPGAU
			HTCGUVFCTMXZKMFQC
			GBEQXXCFEMGCXPKSE
			PGFQCGZESZZCDPMSS
			QFWGZAFIMFQAIZEQZ
			ZAFPIHOFQMXEGBQDU
			CFOAIFHQAIBGSXZAF
			CTTAIQOFBQGHHVOFW
			GOBREAVQUEUZXCJSI
			UFTOTOWDMKQGWFUEF
			WPUOGZCGGGMWRYUGE
			
			*%dZ9|bVz#6S;3Db)
			MKUzd#-F3&.C>yKT:
			zlV5j9DM9:;7yj2bZ
			/XHGAXNlfqFG3X-3T
			kS9<ZN2ATYZy7Mf%)
			H8pUj|RD^Z5zB(dM.
			%MXtNq%M5_j&P:>)>
			+SO&c@:q&y3:(>./5
			Y(/Bb9Z/-;+6SBzU8
			P2LpB%X:/NkAPEjMO
			3X4jO&d6^pP8/Hd#2
			R9_#fP*Dtyk2PK/Z_
			E1F#2R7t:@.2;Ky:Z
			VD5j8MdJCDVAJ7tVY
			@AdKJG+d#pPtjBU;T
			*F+MJD3VMJ9R:P7AD
			*XXASVNdBVkG3&+Dq
			RN9%_b&VO_T7P4W:S
			OFlN^+5;C/UkcDTzd
			qEON1721k1Cq%)Tkt
			
			5
			REQUIRENTTRSINSTA
			MMENTOULTRELACRAN
			CEDUDICTSETONQUIE
			STOITAUSSYDEMMEDE
			SECOURIRETASSISTE
			RMADICTESOEURLARO
			YNEDESCOSSESURQUO
			YJERESPONDISLARCH
			EVESQUEDEGLASCOET
			AUDICTSETONCOMMEA
			USSIFISTMADICTEDA
			MEETMREDESONCOSTQ
			UENOUSAVIONSFAICT
			CEQUIAVOITESTPOSS
			IBLECOMMEENCORENO
			USFAIRIONSTOUJOUR
			SPOURLARESTITUTIO
			NDEMADICTESOEURLA
			ROYNEDESCOSSEMAIS
			PARCEQUELAROYNEMA
			
			MJLZDWZIOOMXDSXOV
			RHZSYJZQOWZGFHWVI
			XZYZINHONZOTILZNJ
			XYTDYFPXXDIJHHZYJ
			NJXTPMDWJYFXXNNOJ
			MHFYDXOJXJZPWQFMT
			DSJIJXXTXXZNZMVPJ
			TEZWZNUJSYDNGVMXM
			ZAJNVZJYJBQVXXTJY
			FPINXOXJYJSHTRRZF
			ZNNNKNXOHVINXOZIF
			HZZYHMJIZNJIXJNOV
			PZSJPXVADJIXKFDXY
			XZLZDVQJDOJXOUTXX
			DWQZHJRRZJIXTWJIT
			PXKVNMDJIXOJZOJZW
			XKJPWGVWJNONOPYDJ
			SYZRFIDHYZXJJZMQF
			WJDSJIZNXJNXZHFNN
			UFWHJVPZGVMTTSZRF
			
			H.5A)CA1GG6BW-dTN
			9LDVc.DzTf%|pLCN1
			j%c41<LG<4*XO5bE.
			_(Y)(@SBdW1.LL7c.
			E._XS6WC.ct&jEPG.
			6LtcW&*.d;4SCUtk:
			W-.1.&BYBdD<AkNS.
			Y#bCJP>.V(W<Fl6_H
			A^;END;(.RKNd&Y;/
			pSOPd*j;(.-L:39Ap
			7PPPZEd*MN1Ej*b1+
			M44/LH;17P;Od.PG8
			SJV.S&N^W.1_ZtW_(
			&D5J)8y;WT;&T>Y_j
			)fy4M.39%;Oj:C;OY
			S&ZlP6W;O_T;qG.Df
			&Z.SfFlf;E*E*Sc).
			-(b3+OWL/DB.;b6z+
			f.)-.OqEd;Ed4L@<E
			>+CM.NS7|N2XYVD3@
			
			9
			SAMEVOLUMETHISNEV
			ERHAPPENEDBYCHANC
			ECLEARLYTHEYAREAC
			QUAINTANCESANDARE
			WORKINGTOGETHERTO
			WARDSOMECOMMONEND
			ISHOULDTHINKITVER
			YLIKELYJUDGINGFRO
			MTHEIRINTERESTINC
			ANCERSANDTOXICOLO
			GYTHATTHEYWEREMED
			ICALSTUDENTSNUMBE
			RSFOURANDFIVEDONT
			EXACTLYSEEMTOSTRE
			NGTHENMYMEDICALHY
			POTHESISBUTTHEYAR
			EONLYTWOOUTOFTHET
			ENTHATSABOUTALLIC
			ANMAKEOUTOFITANDI
			RETURNEDTHELISTTO
			
			JJVVEFULVNKQZJENM
			NIYJGGVWNUSHTQJWL
			NLUNRACHCYVHRIVRL
			HDJZEKRELVJJEMRIV
			NFIBZEPKFXVKYVAKX
			NJAUBFVNLFDVXENWM
			RJYXDCMCQZETZKENI
			HUZBVUPSLMPZEPWAF
			VCYVRIZEKNAVBCZWL
			RWLNIJJWMCFORTFUF
			PHKYRCKYVHNVINDVM
			RLJCJKLUNWCBEDDKV
			AJOFDAREUWZENUXEC
			NOJLCUHBVVVCXBCIV
			WXKYNWDPDVMRLRCYP
			YFKYNJRBSDCKQVHJA
			NXEUHKNXXDKFOKYNK
			VWCYRCJJSXDCRUUZT
			RWVJTVFDKFOZCJEMR
			IVCLIEVMKQNURJKKX
			
			d;y+.Ec5@<N>3;.7P
			7Dtd||y:7TF2q>):8
			<5UjkYW21S+6^D-^8
			_/)L.Nk.5X);.P*DX
			<EGRz.ONEK+J9yYVK
			7;YcRpX75p/yl.<:b
			*;9l/1P1>L.qLN.jD
			_MzR+U#F8HO3.#(YE
			-19y^Gz.NjYXRW3(5
			&(5<D)):P1f%*qETf
			OZNSC1Vt+2<+Dj/XA
			B8dW)N8c<(WR.//N@
			Yd%f/YB.U(L.jMl.1
			7%d51M_R-X+1lR1D@
			(KV9j(/#/-4^5&WtO
			9fV97;&RF/1V>y6)Y
			7l.U6N7KK/Jp%VS<V
			y:WS*WddFK/1^UT3q
			*(ydqXp/NE%3W).P*
			GXW8G.+HN><TB)NVK
			
			8
			TALLOUGHTTOBEHEAL
			THYFELLOWSWITHMYC
			OMMERCIALRATINGAR
			EIMMUNEFROMITIHAP
			PENEDTOBEVISITING
			AFRIENDINASMALLTO
			WNFORAFEWDAYSANDW
			ASACQUIRINGAVORAC
			IOUSAPPETITEONEEV
			ENINGIWASSEIZEDWI
			THASUDDENPAINANDI
			KNEWTHEDREADDISEA
			SEHADCOMEATLASTTH
			EDOCTORCAMEHEWASA
			NOLDFASHIONEDFELL
			OWWITHOUTANYFRILL
			SBUTHEHADWHATBOOK
			SANDCOLLEGESDONOT
			ALWAYSBESTOWAHEAD
			FULLOFCOMMONSENSE
			
			LIDTWMYZLLGTWZMID
			LZGNMDDWOAEABPUGU
			WUEWJUQSTJIBQVYIZ
			MQUUMFWXJWUALAPIH
			XMVWVLGJWNQKABQFY
			INJQWFVQVSAUITTLW
			EFXWZINMELSQKSVLO
			IKSUYMQZQFOIDWZIU
			AGCKSHXMLABMGVWWD
			WVAFOQOSKAWARWLOQ
			LZIKCVVMVXIQFSFVA
			SFMOLZWVJMIVLAKWS
			AMZSVUWUWIBDSALBP
			WVWKBGJKIEWPMOIKI
			FWTVXIAZQWFWVXMTT
			GOOABZGCLSVGXZATD
			ATMBPWZIVEZIBJGGC
			ASVLUGDDMYMAVWFGB
			STOIGATMABGESZWSL
			NCDDGXKWUEGFKWVKM
			
			Y_597F8XYYk9c.F65
			-zk@F*5>U:+dW2)k)
			c)+KHTVbyH/Sq<86N
			1E))1lK&Gj)dY:2/|
			&1<7<YAHK@q%dWD38
			#^HBK3<BtLd)ZR9Y7
			Jl&7zM^FJYbEOL<-U
			/OLT81ENBl4M*jP_T
			:kCOb|&F-:W1ktj>*
			7<d3UB4LO:K:(cYUV
			-z/%C<tF<&#B3Ll<:
			L3FU-zK<H1#<-:Ojb
			d1Pb<T>Tj6WpLd-W2
			><>%SAH%ZJ>2fU/OZ
			3>R<&6:zD7l><&FRR
			kU4:WNA;YLtk&.:9p
			:9fW2jP6tJzMSHAk;
			:Lt-)Ap*F8F:<jlkS
			bRU#A:9fdSAJb.>b-
			@C55A&%cT+k3%KtOf
			
			3
			TOLIFTTHEMORELSEH
			OLESMUSTBECUTINTH
			EMFORTHISPURPOSEV
			IDEFIGFRAMESFORPI
			CTURESORLOOKINGGL
			ASSESTHESEGIVEAWI
			DERANGETOTHEWOODC
			ARVERFORALLBORDER
			SARESUITABLETOFRA
			MESHEADSMAYBEAPPL
			IQUTOCORNERSANDCE
			NTRESOFFRAMESITIS
			VERYMUCHTOBEDESIR
			EDTHATDESIGNERSAN
			DCARVERSWOULDEXER
			TTHEIRINVENTIVENE
			SSANDENDEAVOURTOB
			REAKUPTHEMONOTONY
			ANDFEEBLENESSWHIC
			HCHARACTERIZEMOST
			
			QLILCWQEBPLUBIPBE
			RIBVPRPWYBZXQLKWK
			HJILOQKLPMXUSLVBY
			LGHCLDIODPHVCLOSF
			FQROBVLOOLRNLQJJI
			XVPBVWKHVHDFSHXZL
			ABODKDBQLQEHZLRAF
			XUSBUIRUXIIEROAHU
			PXOHPRLWXEOBWRCUD
			JHPKBDAPJDVYBDSSO
			LTXWRFROQBUPXQAFH
			QWUHPLCIODJHVLQFP
			YBUVPXFKQLYBGHPFU
			HGWEDWGBPFDKBOPXQ
			AFDUYHUPZLXIABABU
			WQEBFUFKYHQQLYBKH
			PVXKGBKGBXSLXOQRY
			OBDNRSQKHJLKRQRKB
			XKGIBBYIHQHVVZEFZ
			KZEDUXFQHULWHPRPQ
			
			y2_HfpyY|LH8|_LKY
			>_MUL>L7+|&S:Hlcl
			P9_V#:q;R3S4%2UK@
			VE*f2(b1WR*Uf;X<O
			Oy/DKj2##H/d;y99_
			5jB|U7qTUP(O%JA&V
			NK1Wq(MyVtYZ&H/GO
			S8<M8_/8^_bk/#NT4
			L^DJB>Hc5Y#F->f4W
			9JLlMWGB9WU@F(<%D
			26A-/O>D:F8RStGOJ
			t78*B2f_D(9Pj;:OB
			@|4UB5Olt;@FCPLO4
			*.7Y(7E|LO(zM#R5y
			NOW8+J8L&HSbG|GM4
			-yYFO8Ol+P:t;+Kl*
			RUSlEMzCKA);51:>+
			#F(d><tzP9;l>:/lF
			AzCbK|+bJ:*UU&kO&
			l&YW8AO:T4H-ZB>Bt

		 */
	}

	public static void testShifts() {
		String alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
		for (int N=1; N<=13; N++) {
			System.out.print(N + " ");
			for (int i=0; i<alpha.length(); i++) {
				char ch = alpha.charAt(i);
				System.out.print(ch+""+shift(ch,-N)+""+shift(ch,N) + " ");
			}
			System.out.println();
		}
	}
	public static void compareJarlve() {
		for (int i=0; i<plaintexts.length; i++) {
			String pt1 = plaintexts[i].toUpperCase();
			String pt2 = plaintextsJarlve[i].toUpperCase();
			if (pt2.length() == 0) continue;
			System.out.println("===== " + (i+1) + " =====");
			System.out.println("Jarl's:");
			System.out.println(pt2);
			System.out.println("Actual:");
			System.out.println(pt1);
			float match = 0;
			for (int j=0; j<pt1.length(); j++) if (pt1.charAt(j) == pt2.charAt(j)) match++;
			match /= pt1.length();
			match *= 100;
			System.out.println("Accuracy: " + match + "%");
			
		}
	}
	public static void main(String[] args) {
//		String cipher = encode(Ciphers.Z408_SOLUTION.substring(0,340), 2);
//		System.out.println(cipher);
//		System.out.println(Arrays.toString(decode(cipher, 2)));
//		makeHomophonics();
//		System.out.println(shift('A',-13));
//		testShifts();
		compareJarlve();
	}
	
}
