package com.zodiackillerciphers.ciphers.generator;

public class ComparePlaintexts {
	public static void compare(String p1, String p2) {
		if (p1.length() != p2.length()) throw new RuntimeException("They are not equal length");
		int hits=0;
		for (int i=0; i<p1.length(); i++) {
			char c1 = p1.charAt(i);
			char c2 = p2.charAt(i);
			if (c1 == c2 || c1 == '_' || c2 == '_') hits++;
		}
		float match = ((float)hits)/p1.length();
		System.out.println(match);
	}
	public static void main(String[] args) {
		compare("ASBEINGONEOFDANTESFAITHFULANDATTACHEDYFRIOENDSANDWASHENOTSOASKEDTHEABBEGASPARDGASPARIDMURMUREDTHEWOMANFROMHERSEATONTHESTAIRSMINDWHATYOUARESAYINGCADEROUSSEMADENOREPLYTOTHESEWORDSTHOUGH__________________EVIDENTLYIRRITATEDANDANNOYEDBYTHEINTERRUPTIONBUTADDRESSINGTHEABBESAIDCANNAMANBEFAITHFULTOANOTHERWHOSEWIFEHECOVETSANDDESIRESFORHIMSELFBUTDAN",
				"ASBEINGONEOFDANTESFAITHRULANDATTACHEDYFRIONNDSANDWASHENOESOASKEDIHEABBEGALPARDGASPTHIDMURMUREDTHEWOMANFROMHERSEARORTHESTAIRSMINDLHATYOUARESAYINGCADEROUSSEMADENOREELYEOOHERELORDSTHOUGHFLADOWPTDLFAAMIKDMEVIAENTLYIRRIEDTEDANDANNOYEDBYEHEINTERRUPNIONBUTADDRESSINGTHEABBESAIRCAETAMANBEFAITHFULTOANOTHERWHOLELIFEHECOVETLANDDESIRESFORHIMSELRBTTDAN");
	}
}
