package com.zodiackillerciphers.corpus;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.zodiackillerciphers.constraints.Info;
import com.zodiackillerciphers.io.FileUtil;

/** process the results file generated by SearchConstraints, then show results sorted by significance. */
public class SearchConstraintsProcessor {
	public static void process(String resultsFile) {
		List<String> lines = FileUtil.loadFrom(resultsFile);
		List<Info> results = new ArrayList<Info>();
		
		int i=0;
		
		for (String line : lines) {
			i++;
			if (i % 1000 == 0) {
				System.out.println("Processing " + i + " of " + lines.size());
			}
			
			if (!line.contains("Constraint match: ")) continue;
			String[] split = line.split(",");
			String file = split[0].substring(30);
			String plain = split[1].substring(1);
			Integer index = Integer.valueOf(split[3].substring(1));
			String sub = split[4].substring(1);
			Float prob = Float.valueOf(split[5].substring(1));
			Info info = new Info(sub, index);
			info.plaintext = plain;
			results.add(info);
			
			
		}
		
		Collections.sort(results);
		for (Info info : results) if (info.enoughUniques()) System.out.println(info);
	}
	
	public static void main(String[] args) {
		process(args[0]);
	}
}
